In [1]:
import numpy as np
import sympy as sp
np.random.seed(53)
A=np.random.randint(0,10,(5,5))
A

array([[9, 5, 5, 6, 4],
       [0, 8, 9, 5, 2],
       [9, 4, 3, 6, 7],
       [9, 9, 7, 3, 6],
       [0, 6, 2, 0, 3]])

In [2]:
B=sp.Matrix(A)
B

Matrix([
[9, 5, 5, 6, 4],
[0, 8, 9, 5, 2],
[9, 4, 3, 6, 7],
[9, 9, 7, 3, 6],
[0, 6, 2, 0, 3]])

In [3]:
U,s,Vt=np.linalg.svd(A)
sp.Matrix(np.round(U))
s

array([26.90109626,  9.79204197,  4.91079107,  2.89185222,  0.98399982])

In [4]:
Sigma=np.zeros((A.shape[0],A.shape[1]))
sp.Matrix(Sigma)

Matrix([
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0]])

In [5]:
Sigma[:A.shape[1],:A.shape[0]]=np.diag(s)
sp.Matrix(Sigma)
sp.Matrix(Vt)


Matrix([
[ -0.51826922010005,  -0.517406808150047, -0.442558260548704, -0.353794947915236, -0.377701643134666],
[ 0.697053862926292,  -0.489221755339434, -0.478084252737306, 0.0789078678751705,  0.199967452236965],
[0.0621153136952316,   0.457094825615533, -0.341847108575764, -0.729239846444097,  0.372230854331863],
[ 0.480150046615291, -0.0242653054975431,   0.38318516042738, -0.475227384421329, -0.629440381298143],
[ 0.105406585260586,   0.532379361289672, -0.558468728302086,  0.333122894246707, -0.531604631557938]])

In [6]:
U@Sigma@Vt

array([[ 9.00000000e+00,  5.00000000e+00,  5.00000000e+00,
         6.00000000e+00,  4.00000000e+00],
       [-2.09335835e-15,  8.00000000e+00,  9.00000000e+00,
         5.00000000e+00,  2.00000000e+00],
       [ 9.00000000e+00,  4.00000000e+00,  3.00000000e+00,
         6.00000000e+00,  7.00000000e+00],
       [ 9.00000000e+00,  9.00000000e+00,  7.00000000e+00,
         3.00000000e+00,  6.00000000e+00],
       [-6.56399752e-16,  6.00000000e+00,  2.00000000e+00,
        -9.52687779e-16,  3.00000000e+00]])

as it is almost equal to our original matrix A singular value decomposition is verified

In [7]:
U1=U[:,:2]
U1=sp.Matrix(U1)
U1

Matrix([
[-0.486888134836206,    0.276783100928548],
[ -0.39577037054519,   -0.757968367859855],
[-0.476872989088543,    0.485656043143325],
[-0.585351118290454, -0.00404129025741262],
[-0.190425782256808,   -0.336150180865147]])

In [8]:
Vt1=Vt[:2,:]
Vt1=sp.Matrix(Vt1)
Vt1

Matrix([
[-0.51826922010005, -0.517406808150047, -0.442558260548704, -0.353794947915236, -0.377701643134666],
[0.697053862926292, -0.489221755339434, -0.478084252737306, 0.0789078678751705,  0.199967452236965]])

In [9]:
Sig1=Sigma[:2,:2]
Sig1=sp.Matrix(Sig1)
Sig1

Matrix([
[26.9010962627597,                0],
[               0, 9.79204197459828]])

In [10]:
A2=U1@Sig1@Vt1
A2

Matrix([
[ 8.67740471982373, 5.45097971279382, 4.50081222449318, 4.84780593118482, 5.48903600217462],
[0.344260284060953, 9.13968500992508, 8.26013501783498, 3.18107462293274, 2.53708973752929],
[ 9.96345257571665, 4.31097915394559,  3.4037566934201, 4.91387674207451, 5.79626818366857],
[ 8.13338709732214, 8.16675092543502, 6.98770103658354, 5.56794026957551, 5.93959849204183],
[0.360498013199617,  4.2608210556146, 3.84073705605466, 1.55263916541722, 1.27662576565674]])

In [11]:
U2=U[:,:3]
U2=sp.Matrix(U1)
U2

Matrix([
[-0.486888134836206,    0.276783100928548],
[ -0.39577037054519,   -0.757968367859855],
[-0.476872989088543,    0.485656043143325],
[-0.585351118290454, -0.00404129025741262],
[-0.190425782256808,   -0.336150180865147]])

In [12]:
Vt2=Vt[:3,:]
Vt2=sp.Matrix(Vt2)
Vt2

Matrix([
[ -0.51826922010005, -0.517406808150047, -0.442558260548704, -0.353794947915236, -0.377701643134666],
[ 0.697053862926292, -0.489221755339434, -0.478084252737306, 0.0789078678751705,  0.199967452236965],
[0.0621153136952316,  0.457094825615533, -0.341847108575764, -0.729239846444097,  0.372230854331863]])

In [13]:
Sig2=Sigma[:3,:3]
Sig2=sp.Matrix(Sig2)
Sig2

Matrix([
[26.9010962627597,                0,               0],
[               0, 9.79204197459828,               0],
[               0,                0, 4.9107910682511]])

In [15]:
A3=U1@Sig1@Vt1
A3

Matrix([
[ 8.67740471982373, 5.45097971279382, 4.50081222449318, 4.84780593118482, 5.48903600217462],
[0.344260284060953, 9.13968500992508, 8.26013501783498, 3.18107462293274, 2.53708973752929],
[ 9.96345257571665, 4.31097915394559,  3.4037566934201, 4.91387674207451, 5.79626818366857],
[ 8.13338709732214, 8.16675092543502, 6.98770103658354, 5.56794026957551, 5.93959849204183],
[0.360498013199617,  4.2608210556146, 3.84073705605466, 1.55263916541722, 1.27662576565674]])