**Row Echelon Form**

In [41]:

import numpy as np
import sympy as sp
np.random.seed(53)
A = np.random.randint(0,10,(5,5))
print(A)

[[9 5 5 6 4]
 [0 8 9 5 2]
 [9 4 3 6 7]
 [9 9 7 3 6]
 [0 6 2 0 3]]


In [42]:
A=sp.Matrix(A)
A

Matrix([
[9, 5, 5, 6, 4],
[0, 8, 9, 5, 2],
[9, 4, 3, 6, 7],
[9, 9, 7, 3, 6],
[0, 6, 2, 0, 3]])

In [43]:
A[2:3,0:5]=A[2:3,0:5]-A[0:1,0:5]
A

Matrix([
[9,  5,  5, 6, 4],
[0,  8,  9, 5, 2],
[0, -1, -2, 0, 3],
[9,  9,  7, 3, 6],
[0,  6,  2, 0, 3]])

In [44]:
A[3:4,0:5]=A[3:4,0:5]-A[0:1,0:5]
A

Matrix([
[9,  5,  5,  6, 4],
[0,  8,  9,  5, 2],
[0, -1, -2,  0, 3],
[0,  4,  2, -3, 2],
[0,  6,  2,  0, 3]])

In [45]:
A[2:3,0:5]=8*A[2:3,0:5]+A[1:2,0:5]
A

Matrix([
[9, 5,  5,  6,  4],
[0, 8,  9,  5,  2],
[0, 0, -7,  5, 26],
[0, 4,  2, -3,  2],
[0, 6,  2,  0,  3]])

In [46]:
A[3:4,0:5]=2*A[3:4,0:5]-A[1:2,0:5]
A

Matrix([
[9, 5,  5,   6,  4],
[0, 8,  9,   5,  2],
[0, 0, -7,   5, 26],
[0, 0, -5, -11,  2],
[0, 6,  2,   0,  3]])

In [47]:
A[4:5,0:5]=8*A[4:5,0:5]-6*A[1:2,0:5]
A

Matrix([
[9, 5,   5,   6,  4],
[0, 8,   9,   5,  2],
[0, 0,  -7,   5, 26],
[0, 0,  -5, -11,  2],
[0, 0, -38, -30, 12]])

In [48]:
A[3:4,0:5]=7*A[3:4,0:5]-5*A[2:3,0:5]
A

Matrix([
[9, 5,   5,    6,    4],
[0, 8,   9,    5,    2],
[0, 0,  -7,    5,   26],
[0, 0,   0, -102, -116],
[0, 0, -38,  -30,   12]])

In [49]:
A[4:5,0:5]=7*A[4:5,0:5]-38*A[2:3,0:5]
A

Matrix([
[9, 5,  5,    6,    4],
[0, 8,  9,    5,    2],
[0, 0, -7,    5,   26],
[0, 0,  0, -102, -116],
[0, 0,  0, -400, -904]])

In [50]:
A[4:5,0:5]=102*A[4:5,0:5]-400*A[3:4,0:5]
A

Matrix([
[9, 5,  5,    6,      4],
[0, 8,  9,    5,      2],
[0, 0, -7,    5,     26],
[0, 0,  0, -102,   -116],
[0, 0,  0,    0, -45808]])